Add error prop to generated vcs compile script
pulp-platform/bender pull request #164
Opened 2024-04-13 03:12 UTC by uge

Change the VCS compile script template to start with a 
```set -e```
to ensure error propagation to fix #163.

2024-04-17 12:57 UTC, micprog requested changes

2024-04-17 12:57 UTC, micprog commented on src/script_fmt/vcs_sh.tera
> +set -e
I think masking this behind the existing `--no-abort-on-error` script option makes sense, for consistency.

```suggestion
{% if abort_on_error %}# Set propagation of error to exit on first error
set -e
{% endif %}
```

2024-04-17 13:43 UTC, uge commented
I wasn't familiar with that flag - thanks for the suggestion.

2024-04-18 11:57 UTC, micprog approved these changes
LGTM! :+1:

2024-04-29 15:43 UTC, micprog approved these changes
LGTM :+1:

2024-04-29 15:57 UTC, merged