Add flags to get sources and scripts for a subset of packages
pulp-platform/bender pull request #70
Opened 2021-12-07 15:33 UTC by micprog

Allows the user to individually specify which packages to include, exclude, and to remove all dependencies from the sources and scripts command. Default behavior (i.e. without the new flags) remains unchanged.

2022-01-05 08:19 UTC, accuminium requested changes
Useful extension that overall LGTM, thanks! I have some suggestions for changes

2022-01-05 08:19 UTC, andreaskurth commented on src/src.rs
> +    /// recursively get dependency names
```suggestion
    /// Recursively get dependency names.
```

2022-01-05 08:19 UTC, andreaskurth commented on src/src.rs
> +    /// Get list of packages bassed on constraints
```suggestion
    /// Get list of packages based on constraints.
```

2022-01-05 08:19 UTC, andreaskurth commented on CHANGELOG.md
> +- Add flags to get sources and scripts for a subset of packages
```suggestion
- Extend the `sources` and `scripts` commands with three flags to work with a subset of packages (`-p`/`--package`, `-e`/`--exclude`, and `-n`/`--no-deps`; see ReadMe or command help for the description).
```

2022-01-05 08:19 UTC, andreaskurth commented on README.md
> +- `-n`/`--no_deps`: Exclude all dependencies, i.e. only top level or specified package(s).
```suggestion
- `-n`/`--no-deps`: Exclude all dependencies, i.e. only top level or specified package(s).
```
This should be a dash to stay consistent with existing flags (e.g., `--complation-mode`, `--no-abort-on-error`).

2022-01-05 08:19 UTC, accuminium commented on src/cmd/script.rs
> +                .long("no_deps")
```suggestion
                .long("no-deps")
```

2022-01-05 08:19 UTC, accuminium commented on src/cmd/sources.rs
> +                .long("no_deps")
```suggestion
                .long("no-deps")
```

2022-01-05 08:19 UTC, accuminium commented on src/cmd/script.rs
> +                .help("Specify package to show sources for.")
```suggestion
                .help("Specify package to show sources for")
```
No other help string for `script` ends with a period (absolute nitpicking, just struck my eye when I ran `script -h` :slightly_smiling_face:).

2022-01-05 08:19 UTC, accuminium commented on src/cmd/script.rs
> +                .help("Exclude all dependencies, i.e. only top level or specified package(s)."),
```suggestion
                .help("Exclude all dependencies, i.e. only top level or specified package(s)"),
```

2022-01-05 08:19 UTC, accuminium commented on src/cmd/script.rs
> +                .help("Specify package to exclude from sources.")
```suggestion
                .help("Specify package to exclude from sources")
```

2022-01-05 08:19 UTC, accuminium commented on src/cmd/sources.rs
> +                .help("Specify package to show sources for.")
```suggestion
                .help("Specify package to show sources for")
```

2022-01-05 08:19 UTC, accuminium commented on src/cmd/sources.rs
> +                .help("Exclude all dependencies, i.e. only top level or specified package(s)."),
```suggestion
                .help("Exclude all dependencies, i.e. only top level or specified package(s)"),
```

2022-01-05 08:19 UTC, accuminium commented on src/cmd/sources.rs
> +                .help("Specify package to exclude from sources.")
```suggestion
                .help("Specify package to exclude from sources")
```

2022-01-05 08:19 UTC, accuminium commented on src/src.rs
> +        }
A `match` statement here leads to redundant code. I suggest to instead use a classic `if` with short-circuit evaluation:
```suggestion
        if self.package.is_none() || packages.contains(self.package.unwrap()) {
            files = self
                .files
                .iter()
                .filter_map(|file| match *file {
                    SourceFile::Group(ref group) => group
                        .filter_packages(packages)
                        .map(|g| SourceFile::Group(Box::new(g))),
                    ref other => Some(other.clone()),
                })
                .collect();
        }
```

2022-01-05 08:22 UTC, accuminium commented
While experimenting with this extension, I found that include directories are currently not affected by the filter mechanisms.

For instance, in the `axi` repo
```sh
$ bender script vsim -e common_cells
# ...
if {[catch {vlog -incr -sv \
    +define+TARGET_SIMULATION \
    +define+TARGET_VSIM \
    "+incdir+$ROOT/.bender/git/checkouts/common_cells-bdd43b87bfd50406/include" \
    "+incdir+$ROOT/include" \
# ...
```
To avoid surprises, we should probably also process the exported include paths with the filtering mechanism. What do you think?

2022-01-05 09:32 UTC, micprog commented
> While experimenting with this extension, I found that exported include directories are currently not affected by the filter mechanisms.
> 
> For instance, in the `axi` repo
> 
> ```shell
> $ bender script vsim -e common_cells
> # ...
> if {[catch {vlog -incr -sv \
>     +define+TARGET_SIMULATION \
>     +define+TARGET_VSIM \
>     "+incdir+$ROOT/.bender/git/checkouts/common_cells-bdd43b87bfd50406/include" \
>     "+incdir+$ROOT/include" \
> # ...
> ```
> 
> To avoid surprises, we should probably also process the exported include directories with the filtering mechanism. What do you think?

My original approach to the include directories was not to worry about them, as they do not specifically reference files, but may have important information for other repositories. As a specific example, the pulp repository exports the `rtl/includes` directory, for which files are included in dependencies such as `pulp_soc` and `pulp_cluster`. Therefore, if you would e.g. only like to synthesize the `pulp_cluster` (`$ bender script synopsys -p pulp_cluster`) and only source these components, removing the include directories form other dependencies would mean not all required include directories are present. 

However, as this is a rather niche use-case with a reasonable workaround (add the include directory to the script manually), and a counter example is also possible (dependency and includes are sourced separately), I agree with the suggestion to keep the behavior consistent. I will make the change, do you think adding a flag (e.g. `--all-include-dirs`) to keep the previous behavior would make sense?

2022-01-05 09:59 UTC, accuminium commented
> My original approach to the include directories was not to worry about them, as they do not specifically reference files, but may have important information for other repositories. As a specific example, the pulp repository exports the `rtl/includes` directory, for which files are included in dependencies such as `pulp_soc` and `pulp_cluster`. Therefore, if you would e.g. only like to synthesize the `pulp_cluster` (`$ bender script synopsys -p pulp_cluster`) and only source these components, removing the include directories form other dependencies would mean not all required include directories are present.

I consider *exporting a directory for use by dependencies* an anti-pattern, because it causes a dependency to effectively depend on its parent. (Configuration should be passed top-down through module parameters. Note that [the coding guidelines we use](https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#parameterized-objects-modules-etc) state "`define` and `defparam` should never be used to parametrize a module".) I think this anti-pattern should not guide our design decisions here.

> However, as this is a rather niche use-case with a reasonable workaround (add the include directory to the script manually), and a counter example is also possible (dependency and includes are sourced separately), I agree with the suggestion to keep the behavior consistent.

Indeed, if users really want to go down that road, they can manually work around the default behavior.

> I will make the change, do you think adding a flag (e.g. `--all-include-dirs`) to keep the previous behavior would make sense?

No, I simply do not see any sane use case that would require this.

2022-01-05 18:37 UTC, micprog commented
Changing the behavior for include directories was a bit more involved than expected, as it was no longer as easy as filtering out a group. This branch now has a related change, limiting the `export_include_dir` to adding incdirs to its own files, as well as packages directly citing this dependency, no longer adding this globally (this handles an open TODO in the code). This may break projects not properly citing the required dependencies.

2022-01-06 07:40 UTC, accuminium approved these changes
LGTM, thanks for implementing the discussed changes!

2022-01-06 08:29 UTC, merged